sudo: required
services:
  - docker

before_install:
  - docker build -t complex-test -f ./client/Dockerfile.dev .

script:
  - docker run complex-test npm test -- --coverage

after_success:
  - docker build -t dewaa97/multi-client ./client
  - docker build -t dewaa97/multi-nginx ./nginx
  - docker build -t dewaa97/multi-server ./server
  - docker build -t dewaa97/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$docker-password" | docker login -u "$docker-username" --password-stdin
  # Take those images and push them to docker hub
  - docker push dewaa97/multi-client
  - docker push dewaa97/multi-nginx
  - docker push dewaa97/multi-server
  - docker push dewaa97/multi-worker